apiVersion: apps/v1
kind: Deploy
metadata:
  name: dogs-deploy
  labels:
    app: dogs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dogs
  template:
    metadata:
      labels:
        app: dogs
    spec:
      containers:
      - name: dogs
        image: 685327363182.dkr.ecr.us-east-1.amazonaws.com/dogs:v1-master
        ports:
        - containerPort: 80
