apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dogs
  name: dogs-pod
spec:
  containers:
  - image: 685327363182.dkr.ecr.us-east-1.amazonaws.com/dogs:v1-master
    name: dogs-container
    ports:
    - containerPort: 80
      hostPort: 8081
