apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: dogs
  name: dogs-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dogs
  template:
    metadata:
      labels:
        app: dogs
    spec:
      containers:
      - image: 685327363182.dkr.ecr.us-east-1.amazonaws.com/dogs:v1-master
        name: dogs
        ports:
        - containerPort: 80
