apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: cats
  name: cats
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats
  template:
    metadata:
      labels:
        app: cats
    spec:
      containers:
      - image: 685327363182.dkr.ecr.us-east-1.amazonaws.com/cats:v-master
        name: cats
        ports:
        - containerPort: 80
